# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

# The branch that will trigger the build when code is commited to it
trigger:
- main

resources:
- repo: self

variables:
  # A tag to track the build number
  tag: '$(Build.BuildId)'

stages:
# Name of the stage  
- stage: Build
  displayName: Build Docker image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      
    - task: Docker@2
      inputs:
        containerRegistry: 'Emmanuel Docker Hub'
        repository: 'emmanuelm777/weatherapi'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: |
          $(tag)

# Name of the stage  
- stage: Provision
  displayName: 'Terraforming on Azure'
  # Which stage this stage depends on (won't run until dependant stage is successfull)
  dependsOn: Build
  jobs:
  # Job name
  - job: Provision
    displayName: 'Provision container instance'
    pool:
      vmImage: 'ubuntu-latest'
    # The name of the library in Azure devops that holds the service principle variables
    variables:
      - group: 'Terraform Service Principle Variables'
    steps:
      - script: |
          set -e

          terraform init -input=false
          terraform apply -input=false -auto-approve
        name: 'run_terraform'
        displayName: 'Run Terraform'
        env: 
          ARM_CLIENT_ID: $(ARM_CLIENT_ID)
          ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
          ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
          ARM_TENANT_ID: $(ARM_TENANT_ID)
          # Set up a terraform variable to pass the build number to main.tf
          # (the substring after TF_VAR_ will be the variable name accessible in main.tf)
          TF_VAR_imagebuild: $(tag)
